CREATE TABLE USUAREIOS (
	Credito NUMBER(4) CHECK (Crédito BETWEEM 0 AND 2000));

ALTER TABLE USUARIO ADD
	(User VARCHAR(10) PRIMARY KEY);

ALTER TABLE USUARIO RENAME COLUMN User TO Login;

CREATE TABLE EMPLEADOS (
	Cod_Cliente VARCHAR(5) PRIMARY_KEY,
	Nombre VARCHAR(10),
	Apellidos VARCHAR(25),
	Sueldo NUMBER(2));
